# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt

name: "Coverage"

on:
  push:
    branches: ["master"]
  # as currently structured, this adds too many jobs (checks?), so don't run it
  # on pull requests yet.
  #pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  coverage:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "2.7"
          - "3.5"
          - "3.9"
          - "pypy3"
        exclude:
          # Windows PyPy doesn't seem to work?
          - os: windows-latest
            python-version: "pypy3"
      fail-fast: false

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install Visual C++ if needed"
        if: runner.os == 'Windows' && matrix.python-version == '2.7'
        run: |
          choco install vcpython27 -f -y

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install -r requirements/ci.pip
          python -m pip install -c requirements/pins.pip tox-gh-actions

      - name: "Run tox coverage for ${{ matrix.python-version }}"
        env:
          COVERAGE_COVERAGE: "yes"
        run: |
          set -xe
          python -m tox
          python -m igor combine_html
          mv .metacov .metacov.${{ matrix.python-version }}.${{ matrix.os }}

      - name: "Upload coverage data"
        uses: actions/upload-artifact@v2
        with:
          name: metacov
          path: .metacov.*

  combine:
    name: "Combine coverage data"
    needs: coverage
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: "0"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install -r requirements/ci.pip
          python setup.py --quiet clean develop
          python igor.py zip_mods install_egg

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: metacov

      - name: "Combine and report"
        run: |
          set -xe
          python -m igor combine_html

      - name: "Upload to codecov"
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml

      - name: "Upload HTML report"
        uses: actions/upload-artifact@v2
        with:
          name: html_report
          path: htmlcov

      - name: Pushes to another repository
        uses: sebastian-palma/github-action-push-to-another-repository@allow-creating-destination-directory
        env:
          API_TOKEN_GITHUB: ${{ secrets.COVERAGE_REPORTS_TOKEN }}
        with:
          source-directory: 'htmlcov'
          destination-github-username: 'nedbat'
          destination-repository-name: 'coverage-reports'
          destination-repository-directory: 'reports/${{ github.sha }}'
          empty-repository: false
          create-destination-directory: true
          target-branch: main
          commit-message: "Coverage report for ${{ github.sha }}"
          user-email: ned@nedbatchelder.com

      - name: Show link to report
        run: |
          echo "https://nedbat.github.io/coverage-reports/reports/${{ github.sha }}/htmlcov"
